<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Recommendation Messages
    |--------------------------------------------------------------------------
    |
    | Localization strings for AI-generated traffic recommendations.
    | These are generated by RecommendationGenerator based on AI predictions.
    |
    */

    'priority_route' => [
        'description' => 'Kích hoạt tuyến ưu tiên cứu hộ — tránh :count đoạn đường bị ảnh hưởng.',
        'message' => 'Tuyến ưu tiên cứu hộ đã kích hoạt. Tránh các khu vực bị ảnh hưởng.',
    ],

    'emergency_alert' => [
        'description' => 'Cảnh báo khẩn cấp cho người dân trong khu vực bị ảnh hưởng.',
        'message' => '⚠️ Sự cố nghiêm trọng. Vui lòng tránh khu vực.',
    ],

    'reroute' => [
        'description' => 'Đề xuất chuyển hướng — dự đoán tắc nghẽn lan rộng :count đoạn.',
    ],

    'congestion_alert' => [
        'description' => 'Cảnh báo ùn tắc — khuyến cáo chọn đường khác.',
        'message' => '⚠️ Ùn tắc nghiêm trọng phía trước. Nên chuyển hướng.',
    ],

    'advisory' => [
        'description' => 'Gợi ý ùn tắc — có thể tắc trong 15–60 phút tới.',
    ],
];
