<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Recommendation Messages
    |--------------------------------------------------------------------------
    |
    | Localization strings for AI-generated traffic recommendations.
    | These are generated by RecommendationGenerator based on AI predictions.
    |
    */

    'priority_route' => [
        'description' => 'Activate priority rescue route — avoid :count affected road segments.',
        'message' => 'Priority rescue route activated. Avoid affected areas.',
    ],

    'emergency_alert' => [
        'description' => 'Emergency alert issued for residents in affected area.',
        'message' => '⚠️ Critical incident. Please avoid the area.',
    ],

    'reroute' => [
        'description' => 'Rerouting recommended — congestion spreading to :count segments.',
    ],

    'congestion_alert' => [
        'description' => 'Congestion warning — consider alternative routes.',
        'message' => '⚠️ Severe congestion ahead. Rerouting recommended.',
    ],

    'advisory' => [
        'description' => 'Traffic advisory — possible congestion in the next 15-60 minutes.',
    ],
];
